spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

api:
  description: "Cards API"
  author: "dfceca0552bda9cedb6bc8c0e1534dff8959aca414250d858cde87d7af63d1b8"
  date: "2024-12-14"
  environment: "PROD"
